#!/bin/bash

echo 'Compile library.'
rake -f ../Rakefile

rm -Rf pkg
echo 'Creating gem'
jruby -S rake gem

echo 'Uninstalling previous gem'
jgem uninstall rmagick4j

echo 'Installing new gem'
jgem install pkg/rmagick4j*
