#!/bin/bash

echo "******** Uninstalling RMagick4J **********"
jgem uninstall rmagick4j

echo "******** Building RMagick4J Gem **********"
jruby -S rake gem

echo "******** Installing RMagick4J Gem **********"
jgem install pkg/*.gem
